FROM treehouses/nginx:latest:
RUN apk add --no-cache \
      fcgi \
    fcgiwrap \
    spawn-fcgi \
      ca-certificates \
      nghttp2-libs \
      libssh2 \
      libcurl \
    curl \
      oniguruma \
    jq
